# Generated by Django 3.2.3 on 2021-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('date', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000000000)),
            ],
        ),
    ]
