# Generated by Django 3.2.3 on 2021-05-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='heading',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
