# Generated by Django 3.2.3 on 2021-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0002_auto_20210521_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
