# Generated by Django 3.2.3 on 2021-05-22 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0004_auto_20210522_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc1',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc10',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc11',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc12',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc13',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc14',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc15',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc2',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc3',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc4',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc5',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc6',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc7',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc8',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='desc9',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='heading',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img1',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img10',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img11',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img12',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img13',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img14',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img15',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img2',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img3',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img4',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img5',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img6',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img7',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img8',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='img9',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints10',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints11',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints12',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints13',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints14',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints15',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints6',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints7',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints8',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='keypoints9',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading13',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading14',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading15',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='subheading9',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
