# Generated by Django 3.2.3 on 2021-05-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0007_auto_20210522_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
