# Generated by Django 3.2.3 on 2021-05-22 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0008_alter_blog_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
